spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=pinkish
    username: sa
    #hoang
    password: hoang
    #Password123!
  jpa:
    show-sql : true
  
logging: 
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
   
security:
  basic:
    enabled : false
    

